stages:
  - build
  - publish

# build:
#   image: 4tqrgqe5yrgfd/electron
#   stage: build
#   script:
#     - yarn make
#   artifacts:
#     expire_in: 1 day
#     paths:
#       - packages/app/desktop/build/installers/*-mac.zip
#       - packages/app/desktop/build/installers/*.exe

# pages:
#   stage: publish
#   script:
#     - mkdir .public
#     - cp -r packages/app/desktop/build/installers/* .public
#     - mv .public public
#   dependencies:
#     - build
#   artifacts:
#     paths:
#       - public/*-mac.zip
#       - public/*.exe
#   only:
#     - main

variables:
  GITLAB_AUTH_TOKEN: $CI_JOB_TOKEN

.make:
  image: 
  stage: build
  script:
    # - cp .env.staging .env
    - yarn make
  cache:
    key:
      files:
        - package.json
        - yarn.lock
    paths:
      - node_modules/
      - .yarn/
    policy: pull-push
  artifacts:
    paths:
      - dist

.publish:
  stage: publish
  image: google/cloud-sdk:300.0.0-alpine
  script:
    - gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
    - gsutil -m cp -r -Z 'dist/*' gs://${BUCKET}/

# staging
make-staging:
  extends: .make
  environment:
    name: staging
  allow_failure: false

publish-staging:
  extends: .publish
  environment:
    name: staging
  variables:
    BUCKET: arkas_releases_staging
    PROJECT: arkas-staging
  need: ["make-staging"]
  allow_failure: false

# production
make-production:
  extends: .make
  environment:
    name: production
  need: ["publish-staging"]
  when: manual
  allow_failure: false

publish-production:
  extends: .publish
  environment:
    name: production
  variables:
    BUCKET: arkas_releases_production
    PROJECT: arkas-production
  need: ["make-production"]
  when: manual
  allow_failure: false

