CREATE TABLE [rapbs] (
  [id_rapbs] varchar(22) NOT NULL, 
  [sekolah_id] varchar(22) NOT NULL, 
  [id_anggaran] varchar(22) NOT NULL, 
  [id_ref_kode] varchar(22) NOT NULL, 
  [id_ref_tahun_anggaran] numeric(4,0) NOT NULL, 
  [kode_rekening] varchar(20) NOT NULL, 
  [id_barang] varchar(40), 
  [urutan] varchar(3), 
  [uraian] varchar(500) NOT NULL, 
  [uraian_text] varchar(255), 
  [volume] numeric(6,0) NOT NULL, 
  [satuan] varchar(30) NOT NULL, 
  [harga_satuan] numeric NOT NULL, 
  [jumlah] numeric NOT NULL, 
  [v1] numeric(4,0), 
  [s1] varchar(30), 
  [v2] numeric(4,0), 
  [s2] varchar(30), 
  [v3] numeric(4,0), 
  [s3] varchar(30), 
  [v4] numeric(4,0), 
  [s4] varchar(30), 
  [keterangan] varchar(2000), 
  [soft_delete] numeric(1,0) NOT NULL DEFAULT 0, 
  [create_date] datetime NOT NULL, 
  [last_update] datetime NOT NULL, 
  [updater_id] varchar(22), 

  CONSTRAINT [sqlite_autoindex_rapbs_1] PRIMARY KEY ([id_rapbs]));