CREATE TABLE [sekolah_penjab] (
    id_penjab varchar(22) NOT NULL, 
    sekolah_id varchar(22) NOT NULL, 
    tanggal_mulai date NOT NULL, 
    tanggal_selesai date NOT NULL, 
    ks varchar(50), 
    nip_ks varchar(20), 
    email_ks varchar(100), 
    telp_ks varchar(20), 
    bendahara varchar(50), 
    nip_bendahara varchar(20), 
    email_bendahara varchar(100), 
    telp_bendahara varchar(20), 
    komite varchar(50), 
    nip_komite varchar(20),   
    soft_delete numeric(1,0) NOT NULL DEFAULT 0,
    create_date datetime NOT NULL,  
    last_update datetime NOT NULL,
    updater_id varchar(22) NOT NULL,
  CONSTRAINT PK_SEKOLAH_PENJAB PRIMARY KEY (id_penjab))